# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  test:
    docker:
      - image: circleci/golang:1.14

    environment:
      GO111MODULE: "on"
      PROJECT_DIR: /go/src/github.com/OWASP/Amass

    working_directory: $PROJECT_DIR

    steps:
      - checkout
      - run:
          name: "Amass Unit Tests and Coverage Reports"
          command: |
            cd $PROJECT_DIR
            go get github.com/OWASP/Amass/v3/...
            go test -coverprofile=coverage.txt -covermode=atomic ./...
      - codecov/upload:
          conf: $PROJECT_DIR/.codecov.yml
          file: $PROJECT_DIR/coverage.txt

workflows:
  version: 2.1
  main:
    jobs:
      - test
#      - binaries:
#          requires:
#            - test
#          filters:
#            branches:
#              only: master
